services:
  mysql:
    image: mysql:8.0
    container_name: shorturl_mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: short_url_system
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet
    # mysql健康检查
    healthcheck:
      # 用mysqladmin ping检测服务是否可用，最准确
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-p123456"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: shorturl_redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-123456}
    ports:
      - "6379:6379"
    networks:
      - mynet
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL","redis-cli -a \"$${REDIS_PASSWORD}\" ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  short_url:
    image: short_url:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short_url
    restart: always
    environment:
      CONFIG_PATH: /app/config/config.docker.yaml
    networks:
      - mynet
    ports:
      - "9090:9090"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:

networks:
  mynet:  

